---
# https://taskfile.dev
version: '3'

tasks:
  goose:
    dir: internal/databases/postgres/migrations

    dotenv:
      - "../../../../app.env"
    cmd: GOOSE_DRIVER=$DB_DRIVER GOOSE_DBSTRING=$DB_URI goose {{.CLI_ARGS}} # yamllint disable-line

  build:
    cmd: go build -o http-server cmd/http/main.go

  start:
    cmd: ./http-server

  install:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/cosmtrek/air@latest
      - go install github.com/kyleconroy/sqlc/cmd/sqlc@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
